language: android
android:
  components:
  - build-tools-22.0.1
  - android-22
  - platform-tools
  - tools
  - add-on
  - extra
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+
branches:
  except:
  - "/^*-v[0-9]/"
script:
- gradle assembleDebug
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=wip-v$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}@github.com/BitSyko/Showcase --tags
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lsyEw2SsEu5CKj9+6bOuS7L2Q+hE9e17kKEEDfbKGYIMvrNAxW/3L+tIhVm1wAXi5HZHP3uYZYG+/dPvGv2Ctq0EUhnHGsXNNt2TS5R5XXPq3MJwtQcQvjbgtP6RJzUDxrf+g2GfolRd+tH22U2jX7JgT3lF21pRW1llYbLqwbcRcZPVKtOvDblw8zA/WWhYi0eRvaCC+2ZNTIRd8XjKwgfs4ZakTKoQxJNZP1Vk4BJ/U5YrAfxZ1v8W8pN1nYuJZPmbQ8MrO94rN390eKth3w01TPwVA1iZOU9VEnNE5BmocCFmJjZAk1TUgpfgeEOA0jLvEskQjv1i398aIoGYXO1FK7/8j9W2LqmVV9N9qcNUBOkvKPjqkOk8D3M7VXtLWkzEvt9V9HUJj3W/OlJIFct78NIyiS0MqQvIzyRsO5NAyEfGBBwjf3rQ7T0NOrll0gI2deaG8w2BGn3UJ9Cj0D02qJwZ0gmr67t96od74Gsc5KDmWrDoelS+Vf6/L40tsquZdWP2ggjP9ATHdHp35T/uK+JQUNzWYIrfJ69g9LPSO1W7JaDpmu2dM+lxg8P1meDLPyJCRW0y4y9t4HWnNuHw7L10/JuRjbnbxIDNobvmVLHU7wJgU1xSlq6NbAeZxBErLlgmK8CwdwYfbQ/mh5nm3qE0LPMPdM69yY7WhAU=
  file: app/build/outputs/apk/Showcase-debug.apk
  on:
    repo: BitSyko/Showcase
    branch: wip
    tags: false
    condition: "$TRAVIS_PULL_REQUEST = false"
env:
  global:
    secure: Kba7H1/eutMzFG5N87y3qQF4owYVMC+tEPg506pjq8RQrV34GttcTyUtIgjVaZdwdWkXLbToglSkqk4b4RC01SEEBNSfTa53ikX7ijql59NUT03p3Zk5y4fqFEZ73nMmUWQ/Q14hkx6qJAnppRYIgMeh++H3AMr639MM/HZCj0OCSprEkqIa5PA4l2AtZ+npmAHHfCSVIQaRiQC/Ui6hGt6EVePJPZK0HJtbJAdJWBPvyJR3gGjzfv+FthxdKgZ6zmJxiqEpUdcJBbDk3TPZfDNg6emQ9jnXf1eWq2uH8r014R5/OOiTyejAoIEmQVTrZEiaYNHTiRaRKgditp8mOxiSdnT1Cnic8eYOC2wPL9us57RtpoRzc1cfhIDiBon9R3NrF9rWTaGgEyl3aI3aTm6IujXpdgUaPEMu+EaihayOZRBw4nE6FXNIoiHdU8yBwPf7stfb9ohnDPfPWKmfjW/vawSFtZxoMcAc9VvyFEi5aJWkgZ7PtUY/oXEVDqNOsax2GQ6FgH/YdNtc1iUKjZDUdI7XYahKq1zVYGlRiJynbCiZThwyA5/IZjWyoMRYy2le+xtCO6W+nTmlGWykAPWwX+kVqGgvA/Nht0EQVC2rIuXhwos7VUq8I1K3GsQ0c4sj7f4UcoqzkqoT7ZTVOYhjMX1DPocXOvN/JlRjPag=
